export const courseDatas = [
	{
		id: 1,
		title: "React Basics",
		description: "Learn the basics of React.",
		date: "20/10/2024",
		students: 1000,
		image: "https://picsum.photos/id/1/200/300",
	},
	{
		id: 2,
		title: "Advanced JavaScript",
		description: "Deep dive into JavaScript.",
		date: "22/10/2024",
		students: 800,
		image: "https://picsum.photos/id/2/200/300",
	},
	// Here's the additional data for 8 more courses:
	{
		id: 3,
		title: "Vue.js Fundamentals",
		description: "Get started with Vue.js for building web applications.",
		date: "25/10/2024",
		students: 700,
		image: "https://picsum.photos/id/3/200/300",
	},
	{
		id: 4,
		title: "Node.js for Beginners",
		description: "Learn how to build server-side applications with Node.js.",
		date: "27/10/2024",
		students: 600,
		image: "https://picsum.photos/id/4/200/300",
	},
	{
		id: 5,
		title: "Git & GitHub Essentials",
		description:
			"Master version control with Git and collaborate effectively on GitHub.",
		date: "29/10/2024",
		students: 900,
		image: "https://picsum.photos/id/5/200/300",
	},
	{
		id: 6,
		title: "Front-End Development with CSS",
		description: "Learn the fundamentals of CSS to style web pages.",
		date: "01/11/2024",
		students: 500,
		image: "https://picsum.photos/id/6/200/300",
	},
	{
		id: 7,
		title: "Building APIs with Express.js",
		description: "Create RESTful APIs using Express.js framework.",
		date: "03/11/2024",
		students: 400,
		image: "https://picsum.photos/id/7/200/300",
	},
	{
		id: 8,
		title: "Introduction to Web Security",
		description:
			"Learn essential web security concepts to protect your applications.",
		date: "05/11/2024",
		students: 300,
		image: "https://picsum.photos/id/8/200/300",
	},
	{
		id: 9,
		title: "Database Management with SQL",
		description: "Learn to query and manage data using SQL language.",
		date: "08/11/2024",
		students: 850,
		image: "https://picsum.photos/id/9/200/300",
	},
	{
		id: 10,
		title: "Building Responsive Websites",
		description: "Create websites that adapt to different screen sizes.",
		date: "10/11/2024",
		students: 650,
		image: "https://picsum.photos/id/10/200/300",
	},
];
